/*
* generated by Xtext
*/
package it.unibo.alchemist.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SapereDSLStandaloneSetup extends SapereDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new SapereDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

