/*
 * generated by Xtext
 */
package it.unibo.alchemist.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SapereDSLRuntimeModule extends it.unibo.alchemist.language.AbstractSapereDSLRuntimeModule {

}
