/*
 * generated by Xtext
 */
package it.unibo.alchemist.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SapereDSLUiModule extends it.unibo.alchemist.language.ui.AbstractSapereDSLUiModule {
	public SapereDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
